project:
  type: book

book:
  title: "Programmieren lernen mit Java"
  subtitle: "Eine Einführung auf Hochschulniveau"
  author: "© [Dominikus Herzberg](https://www.thm.de/mni/dominikus-herzberg)"
  date: today
  date-format: long
  # affilliation: "Technische Hochschule Mittelhessen (THM)"
  chapters:
    - index.qmd
    - Klassen.md
    - KodierungUndRepräsentation.md
  navbar: 
    title: "Programmieren lernen mit Java: Eine Einführung auf Hochschulniveau"
    
  page-footer: 
    center:
      - text: "Impressum"
        href: legal/impressum.md
      - text: "Datenschutzerklärung"
        href: legal/datenschutz.md

# bibliography: references.bib
# csl: citestyle.csl

format:
  html:
    # Theming: https://quarto.org/docs/output-formats/html-themes.html
    theme: cosmo
    title-block-banner: false
    toc: true
    toc-depth: 3
    toc-title: Inhalte
    number-sections: true
    number-depth: 3
    fig-cap-location: margin
    lang: de
  pdf:
    documentclass: scrbook

#  typst:
#    title: "Programmieren lernen mit Java"


