project:
  type: book

book:
  title: "Programmieren lernen mit Java"
  subtitle: "Eine Einführung auf Hochschulniveau"
  author: "© [Dominikus Herzberg](https://www.thm.de/mni/dominikus-herzberg)"
  date: today
  date-format: long
  # affilliation: "Technische Hochschule Mittelhessen (THM)"
  chapters:
    - index.qmd
    - Classes.md
    - KodierungUndRepräsentation.md
  page-footer: 
    center:
      - text: "Impressum"
        href: legal/impressum.md
      - text: "Datenschutzerklärung"
        href: legal/datenschutz.md

# bibliography: references.bib

format:
  html:
    theme: cosmo
    title-block-banner: false
    toc: true
    toc-depth: 2
    toc-title: Inhalte
    number-sections: true
    number-depth: 3
    fig-cap-location: margin
    lang: de
    #format-resources:
    #  - impressum.md
    #  - datenschutz.md
    # footer: "[Impressum](impressum.md) & [Datenschutzerklärung](datenschutz.md) "
    # include-after-body: footer.html
#  pdf:
#    documentclass: scrreprt


