project:
  type: book

book:
  title: "Programmieren lernen mit Java"
  subtitle: "Eine Einf체hrung auf Hochschulniveau"
  author: "[Dominikus Herzberg](https://www.thm.de/mni/dominikus-herzberg)"
  license: "CC BY-NC-ND"
  # https://quarto.org/docs/reference/dates.html#using-a-date-style
  date: today
  date-format: long
  # affilliation: "Technische Hochschule Mittelhessen (THM)"
  chapters:
    - index.qmd
    - Klassen.md
    # - KodierungUndRepr채sentation.md
  navbar: 
    title: "Programmieren lernen mit Java: Eine Einf체hrung auf Hochschulniveau"
    right:
      - text: "CC BY-NC-ND 4.0"
        href: https://creativecommons.org/licenses/by-nc-nd/4.0/deed.de
  # https://quarto.org/docs/websites/website-search.html#search-appearance
  search:
    location: sidebar
    type: textbox
  sidebar:
   # logo: "legal/CC-BC-NC-ND_88x31.png"
   #logo: "legal/by-nc-nd.png"
   text: "Huhu"
  # https://quarto.org/docs/books/book-output.html#sidebar-tools
  repo-url: https://github.com/denkspuren/plj
  repo-actions: [edit,issue,source]
  page-footer: 
    center:
      - text: "Impressum"
        href: legal/impressum.md
      - text: "Datenschutzerkl채rung"
        href: legal/datenschutz.md

# bibliography: references.bib
# csl: citestyle.csl

format:
  html:
    # Theming: https://quarto.org/docs/output-formats/html-themes.html
    theme: cosmo
    title-block-banner: false
    toc: true
    toc-depth: 3
    toc-title: Inhalte
    number-sections: true
    number-depth: 3
    fig-cap-location: margin
    lang: de
    email-obfuscation: javascript
  # pdf:
  #   documentclass: scrbook

#  typst:
#    title: "Programmieren lernen mit Java"


